apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  db_port: '80'
  user-service: user-svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 3001
        env:
        - name: USER_DB_NAME
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: name
        - name: USER_DB_USER
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: user
        - name: USER_DB_PWD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: pwd
        - name: USER_DB_HOST
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: host
        - name: USER_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: db_port
        - name: RGE_RSA
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: rsa
        - name: RGE_RSA_PUB
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: rsa_pub
        - name: USER_HOST
          value: localhost
        - name: USER_PORT
          value: 3001
        - name: USER_OWNER_MAIL
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: owner_mail
        - name: USER_OWNER_PWD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: owner_pwd
        - name: APP_NAME
          value: Punto y Coma
        - name: INFO_HOST #TODO: UPDATE
          value: localhost
        - name: INFO_PORT
          value: '3004'
        - name: ORDER_PORT
          value: '3001'
        - name: ADD_PORT
          value: '3002'
        - name: IA_PORT
          value: '3003'
        - name: ORDER_HOST
          value: localhost
        - name: ADD_HOST
          value: localhost
        - name: IA_HOST
          value: localhost
        - name: MAIL_HOST
          value: smtp.mailtrap.io
        - name: MAIL_PORT
          value: '465'
        - name: MAIL_NAME
          value: PuntoYComa@mail.com
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: mail_user
        - name: MAIL_PWD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: mail_pwd
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    app: user-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
