// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	model "users-service/model"

	mock "github.com/stretchr/testify/mock"
)

// EMPLService is an autogenerated mock type for the EMPLService type
type EMPLService struct {
	mock.Mock
}

// Fire provides a mock function with given fields: from, target
func (_m *EMPLService) Fire(from uint, target uint) error {
	ret := _m.Called(from, target)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(from, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *EMPLService) Get(_a0 uint) (model.UserJobs, error) {
	ret := _m.Called(_a0)

	var r0 model.UserJobs
	if rf, ok := ret.Get(0).(func(uint) model.UserJobs); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.UserJobs)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hire provides a mock function with given fields: _a0, _a1, _a2
func (_m *EMPLService) Hire(_a0 uint, _a1 string, _a2 *model.UserRole) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, *model.UserRole) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HireWaiter provides a mock function with given fields: _a0, _a1, _a2
func (_m *EMPLService) HireWaiter(_a0 uint, _a1 string, _a2 float64) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, float64) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *EMPLService) Search(_a0 uint, _a1 *model.SearchEMPL) ([]model.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.User
	if rf, ok := ret.Get(0).(func(uint, *model.SearchEMPL) []model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *model.SearchEMPL) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchWaiters provides a mock function with given fields: _a0, _a1
func (_m *EMPLService) SearchWaiters(_a0 uint, _a1 *model.Search) ([]model.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.User
	if rf, ok := ret.Get(0).(func(uint, *model.Search) []model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *model.Search) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: from, target, u
func (_m *EMPLService) Update(from uint, target uint, u *model.User) error {
	ret := _m.Called(from, target, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, *model.User) error); ok {
		r0 = rf(from, target, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEMPLService interface {
	mock.TestingT
	Cleanup(func())
}

// NewEMPLService creates a new instance of EMPLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEMPLService(t mockConstructorTestingTNewEMPLService) *EMPLService {
	mock := &EMPLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
