// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	establishment "github.com/modular-project/protobuffers/information/establishment"

	mock "github.com/stretchr/testify/mock"
)

// ESTDService is an autogenerated mock type for the ESTDService type
type ESTDService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *ESTDService) Create(_a0 context.Context, _a1 *establishment.Establishment, _a2 uint32) (uint64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(context.Context, *establishment.Establishment, uint32) uint64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *establishment.Establishment, uint32) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *ESTDService) Delete(_a0 context.Context, _a1 uint64) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: _a0, _a1
func (_m *ESTDService) GetByID(_a0 context.Context, _a1 uint64) (establishment.Establishment, error) {
	ret := _m.Called(_a0, _a1)

	var r0 establishment.Establishment
	if rf, ok := ret.Get(0).(func(context.Context, uint64) establishment.Establishment); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(establishment.Establishment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInBatch provides a mock function with given fields: _a0, _a1
func (_m *ESTDService) GetInBatch(_a0 context.Context, _a1 []uint64) ([]*establishment.Establishment, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*establishment.Establishment
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*establishment.Establishment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*establishment.Establishment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *ESTDService) Update(_a0 context.Context, _a1 *establishment.Establishment) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *establishment.Establishment) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewESTDService interface {
	mock.TestingT
	Cleanup(func())
}

// NewESTDService creates a new instance of ESTDService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewESTDService(t mockConstructorTestingTNewESTDService) *ESTDService {
	mock := &ESTDService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
