// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IsBadder is an autogenerated mock type for the IsBadder type
type IsBadder struct {
	mock.Mock
}

// IsBad provides a mock function with given fields:
func (_m *IsBadder) IsBad() {
	_m.Called()
}

type mockConstructorTestingTNewIsBadder interface {
	mock.TestingT
	Cleanup(func())
}

// NewIsBadder creates a new instance of IsBadder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIsBadder(t mockConstructorTestingTNewIsBadder) *IsBadder {
	mock := &IsBadder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
