// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IsNotFounder is an autogenerated mock type for the IsNotFounder type
type IsNotFounder struct {
	mock.Mock
}

// IsNotFound provides a mock function with given fields:
func (_m *IsNotFounder) IsNotFound() {
	_m.Called()
}

type mockConstructorTestingTNewIsNotFounder interface {
	mock.TestingT
	Cleanup(func())
}

// NewIsNotFounder creates a new instance of IsNotFounder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIsNotFounder(t mockConstructorTestingTNewIsNotFounder) *IsNotFounder {
	mock := &IsNotFounder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
