// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	model "users-service/model"

	mock "github.com/stretchr/testify/mock"
)

// JobStorager is an autogenerated mock type for the JobStorager type
type JobStorager struct {
	mock.Mock
}

// Find provides a mock function with given fields: _a0
func (_m *JobStorager) Find(_a0 string) (model.User, error) {
	ret := _m.Called(_a0)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsVerified provides a mock function with given fields: _a0
func (_m *JobStorager) IsVerified(_a0 uint) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Job provides a mock function with given fields: _a0
func (_m *JobStorager) Job(_a0 uint) (model.UserRole, error) {
	ret := _m.Called(_a0)

	var r0 model.UserRole
	if rf, ok := ret.Get(0).(func(uint) model.UserRole); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.UserRole)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJobStorager interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobStorager creates a new instance of JobStorager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobStorager(t mockConstructorTestingTNewJobStorager) *JobStorager {
	mock := &JobStorager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
