// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Nearester is an autogenerated mock type for the Nearester type
type Nearester struct {
	mock.Mock
}

// Nearest provides a mock function with given fields: ctx, uID, aID
func (_m *Nearester) Nearest(ctx context.Context, uID uint64, aID string) (string, error) {
	ret := _m.Called(ctx, uID, aID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) string); ok {
		r0 = rf(ctx, uID, aID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = rf(ctx, uID, aID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNearester interface {
	mock.TestingT
	Cleanup(func())
}

// NewNearester creates a new instance of Nearester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNearester(t mockConstructorTestingTNewNearester) *Nearester {
	mock := &Nearester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
