// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	model "users-service/model"

	mock "github.com/stretchr/testify/mock"

	pkg "users-service/pkg"
)

// Validater is an autogenerated mock type for the Validater type
type Validater struct {
	mock.Mock
}

// UType provides a mock function with given fields:
func (_m *Validater) UType() pkg.UserType {
	ret := _m.Called()

	var r0 pkg.UserType
	if rf, ok := ret.Get(0).(func() pkg.UserType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pkg.UserType)
	}

	return r0
}

// Validate provides a mock function with given fields: _a0
func (_m *Validater) Validate(_a0 *model.LogIn) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.LogIn) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewValidater interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidater creates a new instance of Validater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidater(t mockConstructorTestingTNewValidater) *Validater {
	mock := &Validater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
